---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

image_pull_secrets:
  - dockerconfigjson

steps:
- name: test
  image: golang:1.14.4
  commands:
  - go test ./...
  
- name: build
  image: golang:1.14.4
  commands:
  - sh scripts/build.sh
  environment:
    GOARCH: amd64
    GOOS: linux

- name: publish
  image: plugins/gcr
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: docker/Dockerfile.server.linux.amd64
    json_key:
      from_secret: google_credentials
    registry: eu.gcr.io
    repo: eu.gcr.io/antha-images/drone
  when:
    event:
    - push
    - tag
